<?php

namespace ContainerVB2r6kj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportPostsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportPostsCommand' shared autowired service.
     *
     * @return \App\Command\ImportPostsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportPostsCommand.php';

        $container->privates['App\\Command\\ImportPostsCommand'] = $instance = new \App\Command\ImportPostsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:import-posts');

        return $instance;
    }
}
